// Major cities across APAC + diaspora-relevant countries.
// Used by the home page location autocomplete and search.
export type City = { city: string; country: string };

export const APAC_CITIES: City[] = [
  // Myanmar
  { city: "Yangon", country: "Myanmar" },
  { city: "Mandalay", country: "Myanmar" },
  { city: "Naypyidaw", country: "Myanmar" },
  { city: "Bago", country: "Myanmar" },
  { city: "Mawlamyine", country: "Myanmar" },
  { city: "Taunggyi", country: "Myanmar" },
  { city: "Monywa", country: "Myanmar" },
  { city: "Pathein", country: "Myanmar" },
  // Thailand
  { city: "Bangkok", country: "Thailand" },
  { city: "Chiang Mai", country: "Thailand" },
  { city: "Phuket", country: "Thailand" },
  { city: "Pattaya", country: "Thailand" },
  { city: "Mae Sot", country: "Thailand" },
  { city: "Hat Yai", country: "Thailand" },
  { city: "Khon Kaen", country: "Thailand" },
  // Singapore
  { city: "Singapore", country: "Singapore" },
  // Malaysia
  { city: "Kuala Lumpur", country: "Malaysia" },
  { city: "Penang", country: "Malaysia" },
  { city: "Johor Bahru", country: "Malaysia" },
  { city: "Kota Kinabalu", country: "Malaysia" },
  { city: "Kuching", country: "Malaysia" },
  { city: "Ipoh", country: "Malaysia" },
  // Indonesia
  { city: "Jakarta", country: "Indonesia" },
  { city: "Surabaya", country: "Indonesia" },
  { city: "Bandung", country: "Indonesia" },
  { city: "Bali (Denpasar)", country: "Indonesia" },
  { city: "Medan", country: "Indonesia" },
  { city: "Yogyakarta", country: "Indonesia" },
  // Philippines
  { city: "Manila", country: "Philippines" },
  { city: "Cebu City", country: "Philippines" },
  { city: "Davao City", country: "Philippines" },
  { city: "Quezon City", country: "Philippines" },
  // Vietnam
  { city: "Ho Chi Minh City", country: "Vietnam" },
  { city: "Hanoi", country: "Vietnam" },
  { city: "Da Nang", country: "Vietnam" },
  { city: "Hai Phong", country: "Vietnam" },
  // Cambodia
  { city: "Phnom Penh", country: "Cambodia" },
  { city: "Siem Reap", country: "Cambodia" },
  { city: "Sihanoukville", country: "Cambodia" },
  // Laos
  { city: "Vientiane", country: "Laos" },
  { city: "Luang Prabang", country: "Laos" },
  // Brunei
  { city: "Bandar Seri Begawan", country: "Brunei" },
  // Timor-Leste
  { city: "Dili", country: "Timor-Leste" },
  // Japan
  { city: "Tokyo", country: "Japan" },
  { city: "Osaka", country: "Japan" },
  { city: "Kyoto", country: "Japan" },
  { city: "Yokohama", country: "Japan" },
  { city: "Nagoya", country: "Japan" },
  { city: "Fukuoka", country: "Japan" },
  { city: "Sapporo", country: "Japan" },
  // South Korea
  { city: "Seoul", country: "South Korea" },
  { city: "Busan", country: "South Korea" },
  { city: "Incheon", country: "South Korea" },
  { city: "Daegu", country: "South Korea" },
  // China
  { city: "Beijing", country: "China" },
  { city: "Shanghai", country: "China" },
  { city: "Shenzhen", country: "China" },
  { city: "Guangzhou", country: "China" },
  { city: "Chengdu", country: "China" },
  { city: "Hangzhou", country: "China" },
  // Taiwan
  { city: "Taipei", country: "Taiwan" },
  { city: "Kaohsiung", country: "Taiwan" },
  { city: "Taichung", country: "Taiwan" },
  // Hong Kong / Macau / Mongolia
  { city: "Hong Kong", country: "Hong Kong" },
  { city: "Macau", country: "Macau" },
  { city: "Ulaanbaatar", country: "Mongolia" },
  // India
  { city: "Mumbai", country: "India" },
  { city: "Delhi", country: "India" },
  { city: "Bengaluru", country: "India" },
  { city: "Hyderabad", country: "India" },
  { city: "Chennai", country: "India" },
  { city: "Kolkata", country: "India" },
  { city: "Pune", country: "India" },
  // Bangladesh / Sri Lanka / Nepal / Pakistan / Maldives
  { city: "Dhaka", country: "Bangladesh" },
  { city: "Chittagong", country: "Bangladesh" },
  { city: "Colombo", country: "Sri Lanka" },
  { city: "Kathmandu", country: "Nepal" },
  { city: "Karachi", country: "Pakistan" },
  { city: "Lahore", country: "Pakistan" },
  { city: "Islamabad", country: "Pakistan" },
  { city: "Malé", country: "Maldives" },
  // Australia / NZ / Pacific
  { city: "Sydney", country: "Australia" },
  { city: "Melbourne", country: "Australia" },
  { city: "Brisbane", country: "Australia" },
  { city: "Perth", country: "Australia" },
  { city: "Adelaide", country: "Australia" },
  { city: "Canberra", country: "Australia" },
  { city: "Auckland", country: "New Zealand" },
  { city: "Wellington", country: "New Zealand" },
  { city: "Christchurch", country: "New Zealand" },
  { city: "Suva", country: "Fiji" },
  { city: "Port Moresby", country: "Papua New Guinea" },
  // Middle East
  { city: "Dubai", country: "United Arab Emirates" },
  { city: "Abu Dhabi", country: "United Arab Emirates" },
  { city: "Sharjah", country: "United Arab Emirates" },
  { city: "Riyadh", country: "Saudi Arabia" },
  { city: "Jeddah", country: "Saudi Arabia" },
  { city: "Doha", country: "Qatar" },
  { city: "Kuwait City", country: "Kuwait" },
  { city: "Manama", country: "Bahrain" },
  { city: "Muscat", country: "Oman" },
  // UK / EU / NA
  { city: "London", country: "United Kingdom" },
  { city: "Manchester", country: "United Kingdom" },
  { city: "Birmingham", country: "United Kingdom" },
  { city: "Edinburgh", country: "United Kingdom" },
  { city: "New York", country: "United States" },
  { city: "Los Angeles", country: "United States" },
  { city: "San Francisco", country: "United States" },
  { city: "Chicago", country: "United States" },
  { city: "Houston", country: "United States" },
  { city: "Seattle", country: "United States" },
  { city: "Washington, D.C.", country: "United States" },
  { city: "Toronto", country: "Canada" },
  { city: "Vancouver", country: "Canada" },
  { city: "Montreal", country: "Canada" },
  { city: "Calgary", country: "Canada" },
  { city: "Berlin", country: "Germany" },
  { city: "Munich", country: "Germany" },
  { city: "Frankfurt", country: "Germany" },
  { city: "Hamburg", country: "Germany" },
  { city: "Paris", country: "France" },
  { city: "Lyon", country: "France" },
  { city: "Amsterdam", country: "Netherlands" },
  { city: "Rotterdam", country: "Netherlands" },
  { city: "Dublin", country: "Ireland" },
];

export const CITY_OPTIONS: string[] = APAC_CITIES.map((c) => `${c.city}, ${c.country}`);
