// APAC + diaspora-relevant countries for HQ selection
export const HQ_COUNTRIES: string[] = [
  "Myanmar",
  "Thailand",
  "Singapore",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Vietnam",
  "Cambodia",
  "Laos",
  "Brunei",
  "Timor-Leste",
  "Japan",
  "South Korea",
  "China",
  "Taiwan",
  "Hong Kong",
  "Macau",
  "Mongolia",
  "India",
  "Bangladesh",
  "Sri Lanka",
  "Nepal",
  "Pakistan",
  "Maldives",
  "Australia",
  "New Zealand",
  "Fiji",
  "Papua New Guinea",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "United Kingdom",
  "United States",
  "Canada",
  "Germany",
  "France",
  "Netherlands",
  "Ireland",
  "Other",
];
