import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Shield, ArrowRight, Lock, CheckCircle, AlertTriangle } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { useLanguage } from "@/hooks/use-language";
import { supabase } from "@/integrations/supabase/client";

/** Permissions that the app recognises for delegate access. */
const ALLOWED_PERMISSIONS = new Set([
  "read_profile",
  "read_jobs",
  "read_applications",
  "read_messages",
  // Legacy permission emitted by useGenerateDelegateToken
  "profile_edit",
]);

/**
 * Token format: generated by useGenerateDelegateToken as `ts_<24 alnum chars>`.
 * Total length is 27. We accept anything >= 20 chars with only [A-Za-z0-9_-] to
 * accommodate minor future format changes.
 */
const TOKEN_FORMAT_RE = /^[A-Za-z0-9_-]{20,}$/;

const DelegateAccess = () => {
  const navigate = useNavigate();
  const { token } = useParams<{ token: string }>();
  const { lang } = useLanguage();
  const [status, setStatus] = useState<"loading" | "success" | "expired" | "invalid" | "maxUsed" | "error">("loading");
  const [errorMessage, setErrorMessage] = useState<string>("");
  const [tokenData, setTokenData] = useState<{ permissions: string[] | null; expires_at: string } | null>(null);

  useEffect(() => {
    const verifyToken = async () => {
      try {
        if (!token) {
          setStatus("expired");
          return;
        }

        // Validate token format before making any network request.
        if (!TOKEN_FORMAT_RE.test(token)) {
          setStatus("invalid");
          return;
        }

        // Use SECURITY DEFINER RPC so we don't expose the delegate_tokens
        // table to general SELECT — only the matching row is returned.
        const { data, error } = await supabase
          .rpc("validate_delegate_token", { _token: token });

        const row = Array.isArray(data) ? data[0] : null;
        if (error || !row) {
          setStatus("expired");
          return;
        }

        // Expiry check: if expires_at is in the past, block access.
        if (row.expires_at && new Date(row.expires_at).getTime() < Date.now()) {
          setStatus("expired");
          return;
        }

        // Usage count check: not tracked in current schema; skipped.

        // Permissions allowlist: filter out any unknown permission strings and warn.
        const rawPermissions: string[] = Array.isArray(row.permissions) ? row.permissions : [];
        const safePermissions = rawPermissions.filter((p) => {
          if (ALLOWED_PERMISSIONS.has(p)) return true;
          console.warn(`[DelegateAccess] Unknown permission stripped: "${p}"`);
          return false;
        });

        setTokenData({ permissions: safePermissions, expires_at: row.expires_at });
        setStatus("success");
      } catch (err) {
        console.error("[DelegateAccess] Token verification failed:", err);
        setErrorMessage(
          lang === "my"
            ? "ဝင်ရောက်ခွင့် စစ်ဆေး၍ မရပါ။ နောက်မှ ထပ်စမ်းကြည့်ပါ။"
            : "Unable to verify access token. Please try again later."
        );
        setStatus("error");
      }
    };
    verifyToken();
  }, [token, lang]);

  if (status === "loading") {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-background px-5">
        <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1.5, ease: "linear" }} className="mb-6 flex h-16 w-16 items-center justify-center rounded-full border-4 border-primary/20 border-t-primary" />
        <p className="text-sm text-muted-foreground">{lang === "my" ? "ဝင်ရောက်ခွင့် စစ်ဆေးနေပါသည်..." : "Verifying access..."}</p>
      </div>
    );
  }

  if (status === "success") {
    const daysLeft = tokenData ? Math.max(0, Math.ceil((new Date(tokenData.expires_at).getTime() - Date.now()) / 86400000)) : 0;
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-background px-5">
        <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} className="mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-emerald/10">
          <CheckCircle className="h-10 w-10 text-emerald" strokeWidth={1.5} />
        </motion.div>
        <h1 className="mb-2 text-xl font-bold text-foreground">{lang === "my" ? "ဝင်ရောက်ခွင့် ရရှိပါပြီ" : "Access Granted"}</h1>
        <p className="mb-1 text-sm text-muted-foreground">
          {lang === "my" ? `ပရိုဖိုင် ပြင်ဆင်ခွင့် · ${daysLeft} ရက်` : `Profile Edit Access · ${daysLeft} days`}
        </p>
        <p className="mb-6 text-xs text-muted-foreground">{lang === "my" ? "ဤ session သည် ပိတ်သွားပါက ထပ်မဝင်နိုင်ပါ" : "This session is stored in memory only"}</p>
        <div className="mb-4 w-full max-w-xs rounded-xl bg-primary/5 p-3">
          <div className="flex items-center gap-2">
            <Lock className="h-4 w-4 text-primary" strokeWidth={1.5} />
            <p className="text-xs text-foreground/80">{lang === "my" ? "ဆက်တင်များ + Delegate စီမံခန့်ခွဲမှု ကန့်သတ်ထားပါသည်" : "Settings & Delegate management restricted"}</p>
          </div>
        </div>
        <Button variant="default" size="lg" className="w-full max-w-xs rounded-xl" onClick={() => navigate("/home")}>
          {lang === "my" ? "ဆက်လက်ရန်" : "Continue"} <ArrowRight className="ml-1.5 h-4 w-4" />
        </Button>
      </div>
    );
  }

  // Invalid token format
  if (status === "invalid") {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-background px-5">
        <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} className="mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-destructive/10">
          <AlertTriangle className="h-10 w-10 text-destructive" strokeWidth={1.5} />
        </motion.div>
        <h1 className="mb-2 text-xl font-bold text-foreground">{lang === "my" ? "တိုကင် မမှန်ကန်ပါ" : "Invalid or expired access token"}</h1>
        <p className="mb-6 text-sm text-muted-foreground">{lang === "my" ? "ဤဝင်ရောက်ခွင့်တိုကင် မမှန်ကန်ပါ" : "This access token is not valid. Please check the link and try again."}</p>
        <Button variant="outline" size="lg" className="w-full max-w-xs rounded-xl" onClick={() => navigate("/")}>
          {lang === "my" ? "ပင်မစာမျက်နှာ" : "Go Home"}
        </Button>
      </div>
    );
  }

  // Token used the maximum number of times
  if (status === "maxUsed") {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-background px-5">
        <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} className="mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-destructive/10">
          <Shield className="h-10 w-10 text-destructive" strokeWidth={1.5} />
        </motion.div>
        <h1 className="mb-2 text-xl font-bold text-foreground">{lang === "my" ? "အသုံးပြုမှု အကန့်အသတ် ပြည့်ပါပြီ" : "Access limit reached"}</h1>
        <p className="mb-6 text-sm text-muted-foreground">{lang === "my" ? "ဤဝင်ရောက်ခွင့်လင့်ခ်ကို အများဆုံး အကြိမ်အရေအတွက် အသုံးပြုပြီးပါပြီ။" : "This access link has been used the maximum number of times."}</p>
        <Button variant="outline" size="lg" className="w-full max-w-xs rounded-xl" onClick={() => navigate("/")}>
          {lang === "my" ? "ပင်မစာမျက်နှာ" : "Go Home"}
        </Button>
      </div>
    );
  }

  // Generic error (network / unexpected)
  if (status === "error") {
    return (
      <div className="flex min-h-screen flex-col items-center justify-center bg-background px-5">
        <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} className="mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-destructive/10">
          <AlertTriangle className="h-10 w-10 text-destructive" strokeWidth={1.5} />
        </motion.div>
        <h1 className="mb-2 text-xl font-bold text-foreground">{lang === "my" ? "အမှားတစ်ခု ဖြစ်ပွားသည်" : "Something went wrong"}</h1>
        <p className="mb-6 text-sm text-muted-foreground">{errorMessage || (lang === "my" ? "နောက်မှ ထပ်စမ်းကြည့်ပါ" : "Please try again later.")}</p>
        <Button variant="outline" size="lg" className="w-full max-w-xs rounded-xl" onClick={() => navigate("/")}>
          {lang === "my" ? "ပင်မစာမျက်နှာ" : "Go Home"}
        </Button>
      </div>
    );
  }

  // Expired / Revoked
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-background px-5">
      <motion.div initial={{ scale: 0 }} animate={{ scale: 1 }} className="mb-6 flex h-20 w-20 items-center justify-center rounded-full bg-destructive/10">
        <AlertTriangle className="h-10 w-10 text-destructive" strokeWidth={1.5} />
      </motion.div>
      <h1 className="mb-2 text-xl font-bold text-foreground">{lang === "my" ? "လင့်ခ် သက်တမ်းကုန်ပြီး" : "Link Expired"}</h1>
      <p className="mb-6 text-sm text-muted-foreground">{lang === "my" ? "ဤဝင်ရောက်ခွင့်လင့်ခ် သက်တမ်းကုန်သွားပါပြီ။ လင့်ခ်အသစ် တောင်းခံပါ။" : "This access link has expired. Please request a new one."}</p>
      <Button variant="outline" size="lg" className="w-full max-w-xs rounded-xl" onClick={() => navigate("/")}>
        {lang === "my" ? "ပင်မစာမျက်နှာ" : "Go Home"}
      </Button>
    </div>
  );
};

export default DelegateAccess;
