
-- Use existing user 07fed0e9 as an employer
INSERT INTO public.employer_profiles (id, company_name, company_description, industry, company_size, hq_country, contact_name, contact_email, contact_phone, company_website, is_verified, verification_status)
VALUES
  ('07fed0e9-2c92-4507-bbab-acf93c46521a', 'TechBridge Myanmar', 'A leading technology consultancy connecting Myanmar talent with global opportunities. We specialize in software development, data analytics, and digital transformation services.', 'Technology', '50-200', 'Singapore', 'Kyaw Min Oo', 'hr@techbridge.sg', '+65 9123 4567', 'https://techbridge.sg', true, 'verified'),
  ('97b69f79-fd54-46c5-8adc-9723b0ec9b03', 'GoldenLand Outsourcing', 'Myanmar-focused BPO company providing customer support, data entry, and virtual assistant services to international clients.', 'Business Services', '200-500', 'Thailand', 'Thida Win', 'recruit@goldenland.co', '+66 81 234 5678', 'https://goldenland.co', true, 'verified');

-- Create realistic jobs
INSERT INTO public.jobs (employer_id, title, title_my, company, description, description_my, requirements, requirements_my, location, job_type, category, role_type, salary_min, salary_max, currency, skills, status, is_verified, is_diaspora_safe, visa_sponsorship, requires_work_permit, payment_methods)
VALUES
  ('07fed0e9-2c92-4507-bbab-acf93c46521a', 'React Frontend Developer', 'React Frontend Developer', 'TechBridge Myanmar', 'We are looking for a skilled React developer to join our growing team. You will work on building modern web applications for international clients. Responsibilities include developing responsive UIs, integrating RESTful APIs, writing clean maintainable code, and collaborating with backend engineers.', 'ကျွန်ုပ်တို့၏ တိုးတက်နေသော အဖွဲ့တွင် ပါဝင်ရန် ကျွမ်းကျင်သော React developer တစ်ဦးကို ရှာဖွေနေပါသည်။', 'Minimum 2 years experience with React.js. Proficiency in TypeScript, Tailwind CSS. Experience with REST APIs and Git. Good English communication skills.', 'React.js နှင့် အနည်းဆုံး ၂နှစ် အတွေ့အကြုံ။ TypeScript, Tailwind CSS ကျွမ်းကျင်မှု။', 'Remote', 'full-time', 'technology', 'developer', 800, 1500, 'USD', ARRAY['React', 'TypeScript', 'Tailwind CSS', 'REST API', 'Git'], 'active', true, true, false, false, ARRAY['Wise', 'Payoneer']),

  ('07fed0e9-2c92-4507-bbab-acf93c46521a', 'Senior Full-Stack Engineer', 'Senior Full-Stack Engineer', 'TechBridge Myanmar', 'Lead development of complex web applications using React and Node.js. Mentor junior developers, conduct code reviews, and collaborate with product managers to deliver high-quality solutions for our enterprise clients.', 'React နှင့် Node.js ကို အသုံးပြု၍ ရှုပ်ထွေးသော web application များကို ဖန်တီးခြင်းတွင် ဦးဆောင်ပါ။', 'At least 4 years full-stack development experience. Expert in React, Node.js, PostgreSQL. Experience with cloud services (AWS/GCP). Strong system design skills.', 'Full-stack development အတွေ့အကြုံ အနည်းဆုံး ၄နှစ်။ React, Node.js, PostgreSQL ကျွမ်းကျင်မှု။', 'Remote', 'full-time', 'technology', 'developer', 2000, 3500, 'USD', ARRAY['React', 'Node.js', 'PostgreSQL', 'AWS', 'System Design', 'TypeScript'], 'active', true, true, false, false, ARRAY['Wise', 'Payoneer', 'Bank Transfer']),

  ('07fed0e9-2c92-4507-bbab-acf93c46521a', 'UI/UX Designer', 'UI/UX ဒီဇိုင်နာ', 'TechBridge Myanmar', 'Design beautiful, intuitive user interfaces for web and mobile applications. Work closely with developers to ensure pixel-perfect implementation. Create wireframes, prototypes, and design systems.', 'Web နှင့် mobile application များအတွက် လှပသော user interface များကို ဒီဇိုင်းဆွဲပါ။', 'Proficiency in Figma or Sketch. Strong portfolio demonstrating UI/UX skills. Understanding of responsive design. Experience with design systems.', 'Figma သို့မဟုတ် Sketch ကျွမ်းကျင်မှု။ UI/UX ကျွမ်းကျင်မှုကို ပြသသော portfolio။', 'Remote', 'full-time', 'design', 'designer', 600, 1200, 'USD', ARRAY['Figma', 'UI Design', 'UX Research', 'Prototyping', 'Design Systems'], 'active', true, true, false, false, ARRAY['Wise', 'Payoneer']),

  ('97b69f79-fd54-46c5-8adc-9723b0ec9b03', 'Customer Support Specialist', 'Customer Support Specialist', 'GoldenLand Outsourcing', 'Handle customer inquiries via chat, email, and phone for our international clients. Resolve issues efficiently while maintaining high customer satisfaction scores. Work in rotating shifts.', 'ကျွန်ုပ်တို့၏ နိုင်ငံတကာ ဖောက်သည်များအတွက် chat, email နှင့် ဖုန်းမှ ဖောက်သည်မေးမြန်းချက်များကို ကိုင်တွယ်ပါ။', 'Excellent English communication skills (written and verbal). Previous customer support experience preferred. Comfortable with shift work. Basic computer skills.', 'အင်္ဂလိပ်ဘာသာ ဆက်သွယ်ရေး ကျွမ်းကျင်မှု (ရေးသားခြင်း နှင့် စကားပြောခြင်း)။', 'Bangkok, Thailand', 'full-time', 'customer-service', 'support', 400, 700, 'USD', ARRAY['English', 'Customer Service', 'Communication', 'Problem Solving'], 'active', true, false, true, true, ARRAY['Bank Transfer']),

  ('97b69f79-fd54-46c5-8adc-9723b0ec9b03', 'Virtual Assistant', 'Virtual Assistant', 'GoldenLand Outsourcing', 'Provide administrative support to international entrepreneurs and small businesses. Tasks include email management, calendar scheduling, data entry, research, and social media management.', 'နိုင်ငံတကာ စီးပွားရေးလုပ်ငန်းရှင်များနှင့် အသေးစား စီးပွားရေးများအတွက် စီမံခန့်ခွဲရေး ပံ့ပိုးမှုပေးပါ။', 'Strong organizational skills. Proficient in Google Workspace and Microsoft Office. Good English skills. Reliable internet connection. Experience with project management tools is a plus.', 'စနစ်ကျသော စီစဉ်နိုင်စွမ်း။ Google Workspace နှင့် Microsoft Office ကျွမ်းကျင်မှု။', 'Remote', 'part-time', 'admin', 'assistant', 300, 500, 'USD', ARRAY['Google Workspace', 'Microsoft Office', 'Data Entry', 'Social Media', 'Organization'], 'active', true, true, false, false, ARRAY['Wise', 'Payoneer']),

  ('97b69f79-fd54-46c5-8adc-9723b0ec9b03', 'Data Entry Operator', 'Data Entry Operator', 'GoldenLand Outsourcing', 'Accurate and efficient data entry for various client projects. Process forms, invoices, and spreadsheets. Maintain data quality standards and meet daily targets.', 'အမျိုးမျိုးသော ဖောက်သည် ပရောဂျက်များအတွက် တိကျပြီး ထိရောက်သော data entry လုပ်ဆောင်ပါ။', 'Fast and accurate typing skills (minimum 50 WPM). Attention to detail. Experience with spreadsheets. Basic English proficiency.', 'မြန်ဆန်တိကျသော စာရိုက်နိုင်စွမ်း (အနည်းဆုံး 50 WPM)။ အသေးစိတ်ကို ဂရုစိုက်ခြင်း။', 'Remote', 'contract', 'admin', 'data-entry', 250, 400, 'USD', ARRAY['Data Entry', 'Excel', 'Typing', 'Attention to Detail'], 'active', true, true, false, false, ARRAY['Wise', 'KBZ Pay']),

  ('07fed0e9-2c92-4507-bbab-acf93c46521a', 'Mobile App Developer (Flutter)', 'Mobile App Developer (Flutter)', 'TechBridge Myanmar', 'Build cross-platform mobile applications using Flutter/Dart. Work with our design team to create smooth, performant mobile experiences. Publish apps to App Store and Google Play.', 'Flutter/Dart ကို အသုံးပြု၍ cross-platform mobile application များကို တည်ဆောက်ပါ။', '2+ years Flutter development. Published apps on App Store or Google Play. Experience with state management (Bloc/Riverpod). Firebase integration experience.', 'Flutter development ၂နှစ်ကျော် အတွေ့အကြုံ။ App Store သို့မဟုတ် Google Play တွင် ထုတ်ဝေပြီးသော app များ။', 'Remote', 'full-time', 'technology', 'developer', 1000, 2000, 'USD', ARRAY['Flutter', 'Dart', 'Firebase', 'iOS', 'Android', 'REST API'], 'active', true, true, false, false, ARRAY['Wise', 'Payoneer']),

  ('07fed0e9-2c92-4507-bbab-acf93c46521a', 'DevOps Engineer', 'DevOps Engineer', 'TechBridge Myanmar', 'Manage cloud infrastructure and CI/CD pipelines. Ensure high availability and security of production systems. Automate deployment processes and monitor system performance.', 'Cloud infrastructure နှင့် CI/CD pipeline များကို စီမံခန့်ခွဲပါ။', 'Experience with AWS/GCP. Proficient in Docker, Kubernetes. CI/CD pipeline experience (GitHub Actions, Jenkins). Linux administration skills. Terraform/IaC experience preferred.', 'AWS/GCP အတွေ့အကြုံ။ Docker, Kubernetes ကျွမ်းကျင်မှု။', 'Remote', 'full-time', 'technology', 'devops', 1500, 3000, 'USD', ARRAY['AWS', 'Docker', 'Kubernetes', 'CI/CD', 'Terraform', 'Linux'], 'active', true, true, false, false, ARRAY['Wise', 'Bank Transfer']);
